spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT:5432}/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

app.admin.username=${APP_ADMIN_USERNAME}
app.admin.password=${APP_ADMIN_PASSWORD}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
