package com.yamicode.lphiebackend;

public enum Role {
    PRESIDENT,
    INTERNAL_VICE_PRESIDENT,
    EXTERNAL_VICE_PRESIDENT,
    TREASURER,
    SECRETARY,
    NEW_MEMBER_EDUCATOR,
    ASSISTANT_NEW_MEMBER_EDUCATOR,
    ACADEMIC_CHAIR,
    ALUMNI_RELATIONS,
    COMMUNITY_SERVICE,
    CULTURAL_CHAIR,
    FUNDRAISING_CHAIR,
    UGC_DELEGATE,
    MULTIMEDIA,
    PR_CHAIR,
    PHILANTHROPY,
    RUSH_CHAIR,
    STROLL_MASTER,
    RISK_MANAGEMENT,
    CHAPTER_ADVISOR
}
