CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL
);

ALTER TABLE members ALTER COLUMN first_name SET NOT NULL;
ALTER TABLE members ALTER COLUMN last_name SET NOT NULL;
ALTER TABLE members ALTER COLUMN role SET NOT NULL;
ALTER TABLE events ALTER COLUMN title SET NOT NULL;
ALTER TABLE events ALTER COLUMN date SET NOT NULL;
ALTER TABLE attendance ALTER COLUMN member_id SET NOT NULL;
ALTER TABLE attendance ALTER COLUMN event_id SET NOT NULL;
ALTER TABLE attendance ALTER COLUMN status SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_attendance_member_event'
    ) THEN
        ALTER TABLE attendance
            ADD CONSTRAINT uk_attendance_member_event UNIQUE (member_id, event_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_attendance_member'
    ) THEN
        ALTER TABLE attendance
            ADD CONSTRAINT fk_attendance_member
            FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_attendance_event'
    ) THEN
        ALTER TABLE attendance
            ADD CONSTRAINT fk_attendance_event
            FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE;
    END IF;
END $$;
